"""empty message

Revision ID: 677386cedacc
Revises: 7f52b9ffe611
Create Date: 2022-09-12 17:33:15.073287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677386cedacc'
down_revision = '7f52b9ffe611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
