"""empty message

Revision ID: 7f52b9ffe611
Revises: 
Create Date: 2022-09-12 16:38:23.834386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f52b9ffe611'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userEmail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('useremail', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userEmail')
    # ### end Alembic commands ###
